### PR TITLE
Segmentation support for InputStreams with known size

### PR DESCRIPTION
**Pull request by infinitydev**
Also added a new constructor to UploadInstructions to enable arbitrary payloads and segmentation plans. The other constructors could probably be changed to public static convenience methods using the new constructor, but I did not want to break stuff for current users.

### CODE REVIEW

**Comment by ferrys** [comment]
connects to #63: Segmentation for uploading objects via InputStream

**Comment by arunazaraiah** [comment]
We are trying to solve this issue and found out that our changes are similar to this pull request.
We are very much interested in this enhancement. Can we have this available soon?

**Comment by ferrys** [comment]
@arunazaraiah definitely! Can you confirm this PR works for the issues you're having?

**Comment by arunazaraiah** [comment]
Yes, it works!!

**Comment by ferrys** [comment]
@arunazaraiah great. I will be sure to prioritize this!

**Comment by arunazaraiah** [comment]
Hi, Any updates or ETA for this PR release?

**Comment by ferrys** [comment]
Hi @arunazaraiah, ideally I would a test for SegmentationPlanBoundedInputStream.java and UploadPayloadBoundedInputStream.java before merging. Is that something you would be interested to adding to this PR?

**Comment by arunazaraiah** [comment]
Sure, I can add tests for SegmentationPlanBoundedInputStream.java and UploadPayloadBoundedInputStream.java

**Comment by arunazaraiah** [comment]
I have the tests ready.

**Comment by ferrys** [comment]
@arunazaraiah Awesome! Can you please create a new PR for the tests and then I'll combine yours and this one together for testing

**Comment by arunazaraiah** [comment]
Here is the PR https://github.com/infinitydev/joss/pull/1

**Comment by ferrys** [comment]
@arunazaraiah thanks! I'll check it out

**Pull request merged**
