### PR TITLE
Issue#85 Complete proxy support

### PR DESCRIPTION
**Pull request by lebe-dev**
Patch adds:

### Complete proxy support

**1. Programmatically way:**

```java
AccountConfig config = new AccountConfig()                                
                         config.setUseProxy(true)
                         config.setProxyHost("hostname")
                         config.setProxyPort(3128);
```

Also you can specify username and password if authentication required:

```java
AccountConfig config = new AccountConfig()
config.setProxyUsername("some-user")
config.setProxyPort("some-password");
```

**2. JVM `net.properties` way:**

Edit `${JAVA_HOME}/jre/lib/net.properties`:

```
java.net.useSystemProxies=true
     
 ...
http.proxyHost=some-host
http.proxyPort=some-port
```

**3. JVM startup options way:**
```
java -Djava.net.useSystemProxies=true \
       -Dhttp.proxyHost=http://PROXY_HOST \
       -Dhttp.proxyPort=PROXY_PORT 
       -Dhttp.proxyUser=USERNAME \
       -Dhttp.proxyPassword=PASSWORD 
       -jar your-app.jar
```

### Upgrade Apache HttpClient library

4.2.1 > 4.5.3

for support `useSystemProperties()`

### CODE REVIEW

**Comment by ferrys** [comment]
Hi @lebe-dev, I'm interested in merging this pull request but I have a few questions first. 

1. Is this related to #86? I would like to merge that PR first.
2. Is there a good way I could test this before merging? I don't have much experience working with proxy servers and I want to make sure this code is as generic as possible.
3. Could you resolve the conflicts with master?

Thanks! I would love to get this merged!

**Comment by lebe-dev** [comment]
Hi @ferrys, thanks. i'll fix it today\tomorrow

**Comment by lebe-dev** [comment]
Hi @ferrys, i has been resolved all conflicts

> Is there a good way I could test this before merging? I don't have much experience working with proxy servers and I want to make sure this code is as generic as possible.

my patch is very simple\generic:

1. Extend `AccountConfig` object (main library configuration entity), add few properties for proxy: server, port, username and password

2. Upgrade Apache Client version for system proxy support

3. One integrational test included but it marked with `@Ignore` annotation.

p.s: you can test "proxy feature" additionally with any public free proxy (i.e. from this list http://www.publicproxyservers.com/proxy/list1.html)

**Comment by ferrys** [comment]
Hi @lebe-dev, merged, thanks for the help! I went ahead and rewrote the IT test a bit so it passed, though it doesn't test proxy authentication support. If you wanted to fix the test so it works and create another PR, I'd be happy to merge it.

**Comment by lebe-dev** [comment]
Hi @ferrys yes i'll append test with authorization as another PR

**Pull request merged**
